### ISSUE TITLE
Timestamp is stored only to the second

### ISSUE THREAD

**Issue by dmurdoch** [hrbrmstr/ulid#2]
This SO posting:  https://stackoverflow.com/q/78554095  points out that the timestamp part of the ULID only stores whole seconds, not milliseconds as documented.  The example code looks like this:

``` r
library(ulid)
gen_ulid <- \(sleep) replicate(5, {Sys.sleep(sleep); generate()})

u <- gen_ulid(.1)
df <- unmarshal(u)
format(df$ts, "%Y-%m-%d %H:%M:%OS3")
#> [1] "2024-05-30 08:04:07.000" "2024-05-30 08:04:07.000"
#> [3] "2024-05-30 08:04:07.000" "2024-05-30 08:04:07.000"
#> [5] "2024-05-30 08:04:08.000"
```

The problem appears to be that the code in `src/wrapper.cpp`  assumes `Rcpp::DatetimeVector` is an integer counting the number of milliseconds, not a double holding seconds (with the milliseconds in the fractional part).

**Comment by eddelbuettel** [comment]
That should be fixable but possibly with a visit to the underlying library and how it exports.  We do store fractional seconds and access them (as we use a double internally, like R). What you describe sounds like a very fixable issue (been there, done that in dealing with 'fractional doubles' for time from milliseconds int counts since epoch etc).

As you have just been in the file can you point me to the line or region or function?

PS Is it just the unmarshaling code?

**Comment by eddelbuettel** [comment]
I think it is in the library itself, or how we use it.  (Note that a simple 'scale by 1e3 missing' is usually screaming more clearly at us by resulting in _grossly wrong_ dates yet here we recover the date the ulid was made, ie now.)  When I print the generated type passed to Rcpp::Datetime we see it is missing sub-second data:

#### Code (with one line added)

```c++
Rcpp::DataFrame unmarshal(std::vector<std::string> ulids) {
    unsigned long sz = ulids.size();
    Rcpp::DatetimeVector dt(sz);
    std::vector<std::string> cv(sz);
    for (unsigned long i=0; i<sz; i++) {
        ulid::ULID u = ulid::Unmarshal(ulids[i]);
        dt[i] = Rcpp::Datetime(ulid::Time(u));
        Rprintf("%20.10f %20.10f\n", (double)u, (double)ulid::Time(u));
        cv[i] = ulids[i].substr(10);
    }
    Rcpp::DataFrame out = Rcpp::DataFrame::create(Rcpp::Named("ts") = dt,
                                                  Rcpp::Named("rnd") = cv);
    return(out);
}
```

#### Output

```sh
edd@rob:~/git/ulid(master)$ local/gh_issue_2.R 
[1] "0001K5GWK5FRBG2X7CWE9BQD2K" "0001K5GWK6TNE3ZNFWNH1408DB" "0001K5GWK6ZMHQ2T7AJGEBXYDF" "0001K5GWK6T5QGFKS9CHSW46FW" "0001K5GWK69A6SX8JC72K5HZ4J"
2075813261861795511321503385780224.0000000000 1717072485.0000000000
2075813263482844651972896080527360.0000000000 1717072486.0000000000
2075813263670691305639994265174016.0000000000 1717072486.0000000000
2075813263464301638953551857188864.0000000000 1717072486.0000000000
2075813262827346518842654804934656.0000000000 1717072486.0000000000
                   ts              rnd
1 2024-05-30 07:34:45 FRBG2X7CWE9BQD2K
2 2024-05-30 07:34:46 TNE3ZNFWNH1408DB
3 2024-05-30 07:34:46 ZMHQ2T7AJGEBXYDF
4 2024-05-30 07:34:46 T5QGFKS9CHSW46FW
5 2024-05-30 07:34:46 9A6SX8JC72K5HZ4J
[1] "2024-05-30 07:34:45.000" "2024-05-30 07:34:46.000" "2024-05-30 07:34:46.000" "2024-05-30 07:34:46.000" "2024-05-30 07:34:46.000"
edd@rob:~/git/ulid(master)$ 
```

**Comment by eddelbuettel** [comment]
Looks like an upstream limitation to me:

```
/**
 * Time will extract the timestamp used to generate a ULID
 * */
inline time_t Time(const ULID& ulid) {
```

Subsecond info is simply not returned.

**Comment by eddelbuettel** [comment]
Taadaa. It works when we use _a different generator_ accessing system clock in millis

```c
Rcpp::CharacterVector generate(long n=1) {
    Rcpp::CharacterVector c(n);
    for (long i=0; i<=(n-1); i++) {
        ulid::ULID u;
        ulid::EncodeTimeSystemClockNow(u);
        c[i] = ulid::Marshal(u);
    }
    return(c);
}
```

and _that one_ we can scale by 1000

```sh
edd@rob:~/git/ulid(master)$ local/gh_issue_2.R 
[1] "01HZ4RFV7RAGH0003ZZY4H6QM0" "01HZ4RFVAXAGH0003ZZY4H6QM0" "01HZ4RFVE1AGH0003ZZY4H6QM0" "01HZ4RFVH5AGH0003ZZY4H6QM0" "01HZ4RFVM9AGH0003ZZY4H6QM0"
2075813980026342825406692224579665920.0000000000 1717073079544.0000000000
2075813980148444333187769771224989696.0000000000 1717073079645.0000000000
2075813980269336915149232688695607296.0000000000 1717073079745.0000000000
2075813980390229497110695606166224896.0000000000 1717073079845.0000000000
2075813980511122079072158523636842496.0000000000 1717073079945.0000000000
                   ts              rnd
1 2024-05-30 07:44:39 AGH0003ZZY4H6QM0
2 2024-05-30 07:44:39 AGH0003ZZY4H6QM0
3 2024-05-30 07:44:39 AGH0003ZZY4H6QM0
4 2024-05-30 07:44:39 AGH0003ZZY4H6QM0
5 2024-05-30 07:44:39 AGH0003ZZY4H6QM0
[1] "2024-05-30 07:44:39.543" "2024-05-30 07:44:39.644" "2024-05-30 07:44:39.744" "2024-05-30 07:44:39.845" "2024-05-30 07:44:39.944"
edd@rob:~/git/ulid(master)$ 
```

**Comment by dmurdoch** [comment]
Great!  Thanks for looking at this.

**Comment by dmurdoch** [comment]
Though I notice the random part is constant in your example...  Presumably easy to fix too.

**Comment by eddelbuettel** [comment]
I noticed that too. And I am sure unit tests would bring it up.

In any event we did demonstrate that a) ulid does store millisecs as claimed but that b) the (very simpler) R accessor demo does not.  So maybe the more prudent bit is to let sleeping beauties rest and re-state second granularity?

**Comment by eddelbuettel** [comment]
See eg https://github.com/suyash/ulid/issues/13

**Comment by eddelbuettel** [comment]
I made a micro-release 0.3.1.1 doocumenting this.

**Comment by eddelbuettel** [comment]
I got this sorted out and will make a new release shortly:

#### Output

```sh
edd@rob:~/git/ulid(feature/upstream_enhancements)$ Rscript local/gh_issue_2.R
[1] "01HZ5MWWWE83CSDH88HWB8555P" "01HZ5MWWZKJWAD5NFAV352JGP7" "01HZ5MWX2QD2K9YJBD8S7E94NF" "01HZ5MWX5V8Z3K38MN84YM7EJ1" "01HZ5MWX8ZJ8JD9TRA86JD3EN2"
[1] "2024-05-30 16:01:07.342" "2024-05-30 16:01:07.443" "2024-05-30 16:01:07.542" "2024-05-30 16:01:07.642" "2024-05-30 16:01:07.743"
Time differences in secs
[1] 0.1010001 0.0999999 0.0999999 0.1000001
                        ts              rnd
                    <POSc>           <char>
1: 2024-05-30 16:01:07.342 83CSDH88HWB8555P
2: 2024-05-30 16:01:07.443 JWAD5NFAV352JGP7
3: 2024-05-30 16:01:07.542 D2K9YJBD8S7E94NF
4: 2024-05-30 16:01:07.642 8Z3K38MN84YM7EJ1
5: 2024-05-30 16:01:07.743 J8JD9TRA86JD3EN2
edd@rob:~/git/ulid(feature/upstream_enhancements)$ 
```

#### Code

```r
#!/usr/bin/env Rscript

library(ulid)
gen_ulid <- \(sleep) replicate(5, {Sys.sleep(sleep); generate()})

u <- gen_ulid(.1)
u
df <- unmarshal(u)
format(df$ts, "%Y-%m-%d %H:%M:%OS3")
diff(df$ts)
data.table::data.table(df)
```

**Comment by eddelbuettel** [comment]
Please try the updated branch or the pull request.  I still need to update the manual pages but the README.md (and test example) now show the millisecond resolution. This may make it a C++17 project too but that is less of an issue these days.

Thanks for bringing this to my attention.

**Comment by markheckmann** [comment]
Just tried it out, working now! :) Thanks a lot for the quick reaction!  🙏🙏 🚀🚀

**Comment by eddelbuettel** [comment]
I got lucky in the sense that someone had identified and fixed the issue in (a fork of) upstream `ulid` (the C++ library) by using `std::chrono` which is something @hrbrmstr and both missed --- but until your post (which @dmurdoch alerted me to) I had sort-of glossed over this.  I then only need to deal with the trickery of getting `POSIXct` to and from `std::chrono`

Will merge the branch, update some more docs. extend tests and make a 0.4.0 release in the next few days.

**Comment by eddelbuettel** [comment]
~Turns out this _does_ not in fact work on Windows.~  False alarm.  In correcting for a specific nag from CRAN I made a thinko, which I since corrected.  Appears we work on all three major platforms.
